dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - '12'
  - '10'
  - '8'
cache:
  directories:
    - node_modules

before_script:
  - sudo apt-get install openjdk-8-jdk
  - sudo apt-get install curl
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - sudo apt-get update && sudo apt-get install bazel
  - sudo apt-get install --only-upgrade bazel

stages:
  - lint
  - test
  - npm release
script:
  - 'npm run test:unit'
jobs:
  include:
    - stage: lint
      node_js: '10'
      script: 'npm run lint'
    - stage: npm release
      node_js: '10'
      script: skip
      after_success:
        - npx semantic-release
branches:
  only:
    - master
